### ISSUE TITLE
@Rules of outer class are not applied to the instance of the outer class

### ISSUE THREAD

**Issue by UrsMetz** [bechte/junit-hierarchicalcontextrunner#26] opened 2016-03-09 14:32 UTC
When using junit-hierarchicalcontextrunner together with Mockito's JUnit rule (e.g. `MockitoJUnitRule` or `MockitoJUnit.rule()` in newer versions) depending on where the mocks are defined (in the outer class or the inner class) some mocks aren't instantiated (cf. also mockito/mockito#353). I think this also applies to other JUnit rules that manipulate the test instance.

In the following example the `@Mock` annotated instance variable of type `Runnerable` is not instantiated (and the test fails with a `NullpointerException`):

``` java
@RunWith(HierarchicalContextRunner.class)
public class HierarchicalMockitoTest {
    @Rule
    public MockitoRule mockitoRule = MockitoJUnit.rule();

    @Mock
    private Runnable runnable;

    public class Context {
        @Test
        public void test() throws Exception {
            runnable.run();
        }
    }
}
```

When the mock is made an instance variable of `HierarchicalMockitoTest$Context` everything works as expected.

When debugging one sees that junit-hierarchicalcontextrunner correctly applies the rule onto the instance of `HierarchicalMockitoTest$Context` but not onto the instance of the outer class. I think the way junit-hierarchicalcontextrunner evalutes rules should be changed to also apply them to outer classes. But I wanted to start a discussion about it to see whether there are reasons against this change in behaviour. I could take a stab in case the change in behaviour is wanted.

**Comment by bechte** [comment] 2016-03-09 18:37
Hi. 

Thank you for analyzing this issue in such detail. it absolutely makes sense to apply the rules as you have described. I would be happy if you could prepare a pull request or some ideas how to solve this issue. I am very limited in time lately.

best Stefan

**Comment by UrsMetz** [comment] 2016-03-12 18:30
@bechte I working on a fix right now but I have two questions:

1. In [HierarchicalRunRulesStatementBuilder, currently line 41](https://github.com/bechte/junit-hierarchicalcontextrunner/blob/e3644ee1a400f771cc1b9163bc073f6ec440a965/src/main/java/de/bechte/junit/runners/context/statements/builder/HierarchicalRunRulesStatementBuilder.java#L41) there is a test whether the list of `TestRule`s found contains a `MethodRule`. My IDE marks this as always yielding `false` (which I think is a true statement). Could/should this condition be removed, maybe in another pull request or separate commit?
1. I could imagine that JUnit rules that lock global resources like a network port (e.g. by starting a server) could fail with this change of behaviour (depending on there implementation). So this could be a breaking change.

For 2. a possible workaround could be a wrapper rule that ensures that the wrapped rule is only applied once. But I have not investigated this further.

**Comment by bechte** [comment] 2016-03-14 08:41
@UrsMetz Cool. About your questions:

1. I could imagine of implementations that implement both, `MethodRule` and `TestRule`. Therefore, this expression could (in very rare cases) yield to `true`. Still, I think your suggestion to remove it is right, because one that implements both, should be guaranteed to be called twice. Therefore, please feel free to remove this `if`-statement. A separate commit will do.

2. From the interpretation above, the expected behaviour would be to be called twice. So, I would call it a bug fix. What do you think?

**Comment by UrsMetz** [comment] 2016-03-14 17:14
1. I didn't think of the case that a rule might implement both interfaces. I will check what the behaviour of JUnit for non-hierarchical ("normal") tests is. In case it only executes the rule once I will leave the current check in. Otherwise I will remove it.
1. Writers of rule might not have had thought that there rules could be applied several times for one test case (because that does not happen for "normal" JUnit tests) so I think there is a risk of breaking those rules (in a way this also relates to 1.).

**Comment by bechte** [comment] 2016-03-14 18:21
1: great! sounds like a plan. 

Concerning 2: If I get it right, rules are only applied once for hierarchies. at least they should. they must be applied onto the test instance of the hierarchy in which they are defined. so, having a two, a outer and a nested class, with both of them defining a rule, both rules are applied for tests within the nested test class. the outer is applied on the test instance object of the outer instance while the nested is applied on the inner test instance object.

Does this make sense?

**Comment by UrsMetz** [comment] 2016-03-16 20:49
I check JUnit's  behaviour: it only evaluates rules that both implement `TestRule` and `MethodRule` once. So I left that behaviour in. I still want to tweak the code and tests before sending a pull request. I hope I can get it ready by tomorrow or Friday.

Concerning 2: I think my abstract example is not clear enough, so here is a concrete one :-):
```java
public class TestWithTestRuleOnHighestLevel {
    @Rule
    public MethodRuleBlockingAGobalResource rule = Server.startOnPort(8080);

    public class Context {
        @Test
        public void aTest() throws Exception {
            ...
        }
    }
}
```
In that case the fix discussed in this issue breaks the existing test (in case the rule doesn't check whether the server is not already running).

**Comment by bechte** [comment] 2016-03-17 05:35
Well, in your example, a second test on the outer class level would also break, wouldn't it? Rule must verify that they can be called once per test, so I don't think this change will break anything. 

We should make sure that class rules (static ones, see http://junit.org/javadoc/latest/org/junit/ClassRule.html) are only applied once. Have you been thinking of these? :smile: Those are handled separately.

**Comment by UrsMetz** [comment] 2016-03-18 17:57
Maybe I'm just too worried ;-).

As `ClassRule`s are handled by a different statement builder I think my changes won't interfere with their handling.

I'm still not finished with the change because I just realized today that my initial implementation also applied the rules to higher hierarchy levels. But nevertheless I would like to open a pull request with the current state so you could have a look and I could push new commits to the branch used for the pull request as I fix the open issues. Or would you prefer that I only open a pull request when I consider the change to be complete and finished?
With the first option we could also discuss how to test it because the unit tests I wrote are getting a bit messy and maybe a different approach would be better.

**Comment by bechte** [comment] 2016-03-19 17:03
Sure, feel free to create a PR. :+1:

**Comment by mvitz** [comment] 2016-10-19 10:32
Any chance that this will be merged soon? I stumbled over exactly this issue and would like to see this merged ;-)

**Comment by bechte** [comment] 2016-10-26 23:06
Thanks for pinging me on this one. I forgot to do this. I will try to merge it by the end of October. Sorry for the huge delay.

**Comment by UrsMetz** [comment] 2016-10-28 20:27
@bechte I'd be happy to see my PR merged but I think we should first have a short discussion regarding my questions in #28: as far as I remember there might be some test cases missing.

**Comment by QAston** [comment] 2016-11-24 11:46
Pinging @bechte once again, as we are approaching the end of november.

**Comment by bechte** [comment] 2017-01-12 18:27
merged

**Comment by bechte** [comment] 2017-01-12 18:27
thanks for the work 😄

**Closed by bechte** 2017-01-12 18:27 UTC
